nz_supply_chain:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: postgres
      password: postgres
      port: 5433 # <--- MUST match your docker-compose '5433:5432' mapping
      dbname: nz_supply_chain
      schema: public
      threads: 1
